version: "3.9"

services:
  proxy:
    image: nginx:latest
    ports:
      - "8090:80"
    networks:
      backend:
        ipv4_address: 172.20.0.2

  web:
    image: cr.yandex/crp9mghfl62emh4c90cu/test:latest
    container_name: web
    restart: always
    env_file: .env
    networks:
      backend:
        ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.0.10

volumes:
  db_data:

networks:
  backend:
    external: true
    name: netology2_backend
